version: '3.8'
services:
  bookmarker-db:
    image: postgres:14-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '15432:5432'